---
- name: Check AWS configuration
  fail:
    msg: |-
      Did you remember to copy extra_vars.yml.example to extra_vars.yml
          and configure it appropriately?
  when:
    - aws_secret_key is not defined

- name: Destroy resources
  shell: tofu destroy -auto-approve -var-file="ansible.tfvars"
  args:
    chdir: "{{ (current_project_dir, 'roles/vm/terraform') | path_join }}"
  register: aws_ec2_destroy_result

- name: Display EC2 instance deletion output
  debug:
    msg: "{{ aws_ec2_destroy_result.stdout }}"
