---

# Since unzip is not available in sle-micro, this is a workaround.
- name: Install unzip package required to install opentofu on sle-micro
  become: true
  shell: |
    transactional-update --continue -n pkg install --auto-agree-with-licenses https://download.opensuse.org/distribution/leap/15.6/repo/oss/{{ ansible_facts.architecture }}/unzip-6.00-150000.4.11.1.{{ ansible_facts.architecture }}.rpm
  when: ansible_distribution == 'SL-Micro'

# - name: Install Longhorn dependency packages
#   become: true
#   community.general.zypper:
#     name: ["open-iscsi", "nfs-client", "nfs-utils", "cryptsetup", "device-mapper"]
#     state: latest
#     update_cache: true
#   register: install_suse_packages_result
#   until: "'rc' not in install_suse_packages_result or install_suse_packages_result.rc == 0"
#   retries: 10
#   delay: 60
#   when: cloud_provider == "aws" and enable_longhorn | default(false)
