---
#
# Cloud provider in which the VM will be created. The acceptable values
# are "local" or "aws".
#
# If cloud provider is "local", the VM will be created locally using libvirt.
# If cloud provider is "aws", the VM will be created in AWS via terraform.
#
cloud_provider: local

##################################################################
# These configuration are only applicable to VM created on the   #
# local host. In other words, they are only meaningful if the    #
# cloud_provider is "local".                                     #
##################################################################

# URL to download the cloud image
cloud_image_download_url: https://download.suse.de/download/ibs/SUSE/Products/SL-Micro/6.0/x86_64/SL-Micro.x86_64-6.0-Default-qcow-GM.qcow2 
#cloud_image_checksum_url: "sha256:{{ cloud_image_download_url }}.sha256"

# Image name for identification purposes
cloud_image_os_name: SL-Micro-6.0.0

# OS variant for libvirt optimization. See virt-install --os-variant
vm_os_variant: sle15

# Directory for libvirt images. Make sure current
# user write access to this dir.
libvirt_images_dir: ./libvirt_images

# destination file name for the downloaded cloud image
cloud_image_file: "{{ libvirt_images_dir }}/{{ cloud_image_os_name }}.img"

# determine whether to force re-download cloud image
force_cloud_image_download: false

# VM disk image file name for the VM instance
disk_image_file: "{{ libvirt_images_dir }}/{{ cloud_image_os_name }}-{{ vm_instance_name }}-instance.qcow2"

# size of the disk image
disk_image_size: 50G

# cloud configuration image file name
cloud_config_image_file: "{{ libvirt_images_dir }}/{{ cloud_image_os_name }}-{{ vm_instance_name }}-instance-cidata.iso"

# VM instance configurations
#
# NOTE: for an AI stack, make sure we have plenty of memory and CPUs since
# it is resource-intensive to train and run the models.
#
vm_memory: 32768
vm_vcpus: 8
# NOTE: default VM user is ai.
vm_user_plain_text_password: aiyaya

# root user password (in plain text, not the hash)
vm_root_user_plain_text_passwd: linux

suse_packages: ["jq", "python3-PyYAML", "curl", "git", "selinux-tools"]

reboot_wait_timeout: 540
