- name: Mount the additional NVMe SSD disk
  shell: |
    #!/bin/bash

    # Find all nvme block devices
    devices=$(lsblk -n -o NAME,TYPE | grep disk | grep nvme | awk '{print $1}')

    for device in $devices; do
        mount_point=$(grep -w "/dev/$device" /proc/mounts | grep nvme | awk '{print $2}')
        fs_type=$(sudo file -s /dev/$device)
        if [[ -z $mount_point && "$fs_type" == *": data" ]]; then
            echo "Did not locate a filesystem on /dev/$device and mount point does not exists. Using $device as additional disk"
            TYPE="xfs"
            UUID=$(uuidgen)
            DEV_PATH="/dev/$device"
            # Create file system with ext4. Note: Cannot use ext4 because kafka does not like lost+found folder created as part of mkfs.ext4
            #sudo mkfs -U ${UUID} -L DATA -t ${TYPE} ${DEV_PATH}
            
            # Create file system with xfs
            sudo mkfs.xfs -m uuid=${UUID} ${DEV_PATH}

            MOUNT_PATH={{ longhorn_additional_disk_mount_path }}

            if ! [ -d $MOUNT_PATH ]; then
              sudo mkdir -p ${MOUNT_PATH}
            fi

            sudo mount ${DEV_PATH} ${MOUNT_PATH}

            # Update the fstab to persist after reboot
            sudo su -c "echo 'UUID=${UUID} ${MOUNT_PATH} ${TYPE} defaults,discard,nofail 0 0' >> /etc/fstab"

            break
        fi
    done
  register: result

- name: Show result
  debug:
    msg: "{{ result.stdout }}"