---
- name: Install and configure SUSE AI Factory entirely from Harbor
  hosts: aif_management
  gather_facts: true
  become: true
  environment:
    PATH: /usr/local/bin:/var/lib/rancher/rke2/bin:/usr/sbin:/usr/bin:/sbin:/bin
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  vars:
    airgap_ca_source: "{{ playbook_dir }}/../generated/pki/ca.crt"
  roles:
    - role: aif_airgap_install
