---
longhorn_helm_repo_name: longhorn
longhorn_helm_repo_url: https://charts.longhorn.io
longhorn_helm_chart_ref: longhorn/longhorn
longhorn_namespace: longhorn-system
longhorn_release: longhorn
longhorn_chart_version: 1.7.2
longhorn_username: admin
longhorn_password: longhorn
longhorn_hostname: suse-longhorn

longhorn_additional_disk_mount_path: "/opt/longhorn"

