---
# Pin the driver version that's known to work
- name: Set driver version
  set_fact:
    driver_version: "{{ nvidia_driver_sles_version if ansible_distribution == 'SLES' else nvidia_driver_sle_micro_version }}"

- name: Print driver version
  debug:
    msg: "Use driver version {{ driver_version }}"

- name: Add NVIDIA graphics drivers for SLE repo
  become: true
  community.general.zypper_repository:
    name: nvidia-sle15sp6-main
    repo: 'https://download.nvidia.com/suse/sle15sp6/'
    state: present
    auto_import_keys: true
    runrefresh: true
