- name: Create secret for application collection
  shell: |
    max_retries=10
    delay=30
    SECRET_NAME={{ appco_secret }}
    for retry in $(seq 1 $max_retries); do
      if ! kubectl get secrets -n {{ suse_private_ai_namespace }} -o json | jq -r ".items[].metadata.name" | grep $SECRET_NAME;then
        status=$(kubectl create secret docker-registry {{ appco_secret }} --docker-server=dp.apps.rancher.io --docker-username={{ application_collection_user_email }} --docker-password={{ application_collection_user_token }} -n {{ suse_private_ai_namespace }})
        if [[ "$status" == *"created"* ]]; then
          exit 0
        else
          sleep $delay
        fi
      fi
    done
