####################################################################
# Per https://docs.ranchermanager.rancher.io/pages-for-subheaders/ #
# install-upgrade-on-a-kubernetes-cluster                          #
####################################################################

- name: Add Rancher helm repo
  kubernetes.core.helm_repository:
    repo_url: "{{ rancher_helm_repo_url }}"
    name: "{{ rancher_helm_repo_name }}"

- name: Copy rancher-values.yaml
  template:
    src: rancher-values.yaml.j2
    dest: ~/rancher-values.yaml

- name: Deploy latest rancher helm chart
  shell: >
    helm upgrade --install {{ rancher_release }} {{ rancher_helm_chart_ref }} --atomic \
    --version {{ rancher_version }} --create-namespace --namespace {{ rancher_namespace }} \
    -f rancher-values.yaml
  register: rancher_deploy_result
  until: rancher_deploy_result.rc == 0
  retries: 3
  delay: 20

- name: Wait for Rancher to be rolled out
  shell: >
    kubectl -n {{ rancher_namespace }} rollout status deploy/{{ item }}
  register: rancher_rollout_result
  retries: 10
  delay: 30
  with_items:
    - "{{ rancher_release }}"
    - "{{ rancher_release }}-webhook"
  until: "'successfully rolled out' in rancher_rollout_result.stdout"

# per https://github.com/rancher/local-path-provisioner
- name: Install local-path storage provisioner
  shell: >
    kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.28/deploy/local-path-storage.yaml
