- name: Copy get_rancher_admin_token.sh script
  copy:
    src: files/get_rancher_admin_token.sh
    dest: ~/get_rancher_admin_token.sh
    mode: "0755"

- name: Generate Rancher admin token
  shell: |
    bash ~/get_rancher_admin_token.sh https://{{ rancher_host }} admin {{ rancher_bootstrap_password}}
  register: rancher_token_result
  no_log: true

- name: Confirm Rancher admin token generation
  debug:
    msg: "Rancher API token generated (value redacted)."

- name: set rancher token
  set_fact:
    rancher_token: "{{ rancher_token_result.stdout }}"
  no_log: true

- name: Display Rancher URL
  debug:
    msg: "https://{{ rancher_host }}"
