---
############################################################################
# Per https://cert-manager.io/docs/installation/helm/#installing-with-helm #
############################################################################

- name: Add cert-manager helm repo
  kubernetes.core.helm_repository:
    repo_url: "{{ cert_manager_helm_repo_url }}"
    name: "{{ cert_manager_helm_repo_name }}"

- name: Deploy cert-manager helm chart
  shell: >
    helm upgrade {{ cert_manager_release }} {{ cert_manager_helm_chart_ref }} --install --atomic --create-namespace --namespace {{ cert_manager_namespace }} --set installCRDs=true
  register: cert_manager_install_result
  retries: 5
  delay: 30
  until: cert_manager_install_result.rc == 0


- name: Wait for cert-manager to be rolled out
  shell: >
    kubectl -n {{ cert_manager_namespace }} rollout status deploy/{{ cert_manager_release }} --timeout=120s
  register: cert_manager_rollout_result
  retries: 5
  delay: 10
  until: "'successfully rolled out' in cert_manager_rollout_result.stdout"
