- name: Deploy Rancher onto Mgmt Cluster
  hosts: mgmt_cp_master
  tasks:
    - name: Deploy Cert-Manager
      import_role:
        name: cert-manager

    - name: Deploy external-dns
      import_role:
        name: external-dns
      vars:
        owner: mgmt-dev-{{ hostvars['localhost']['unique_id'] | default('') }}
      when: enable_external_dns | default(false)

    - name: Set target when no external-dns
      set_fact:
        mgmt_target: "{{ ansible_host }}"
      when: not ( enable_external_dns | default(false))

    - name: Set target when external-dns
      set_fact:
        mgmt_target: "{{ hostvars['localhost']['ingress_fqdn'] }}"
      when: enable_external_dns | default(false)

    - name: Set rancher password
      set_fact:
        rancher_password: "{{ rancher_bootstrap_password }}"

    - name: Deploy Rancher
      import_role:
        name: rancher

    - name: Install Longhorn
      import_role:
        name: longhorn
      vars:
        target: "{{ mgmt_target }}"
        lhost: "{{ hostvars['localhost']['longhorn_host'] }}"
      when: (cloud_provider | default('local')) == "aws" and enable_longhorn
