- name: Deploy RKE2 on the Mgmt Cluster - CP Master
  hosts: mgmt_cp_master
  tasks:
    - name: Deploy RKE2 master
      import_role:
        name: rke2
      vars:
        rke2endpoint: "{{ hostvars['localhost']['kubeapi_fqdn'] }}"
        service_name: "rke2-server"
        token: "{{ cluster.token | default('mgmt-rke2token') }}"
        version: "{{ cluster.version | default('v1.30.5+rke2r1') }}"
        role: control-plane-master

    #https://github.com/NVIDIA/gpu-operator/issues/992#issuecomment-2796578769
    - name: Update PATH
      become: true
      shell: |
        echo PATH=$PATH:/usr/local/nvidia/toolkit >> /etc/default/rke2-server

    - name: Read kubeconfig from master node
      ansible.builtin.slurp:
        src: "/home/{{ vm_ansible_user | default('ai') }}/.kube/config"
      register: mgmt_kubeconfig_data
      become: true

    - name: Set kubeconfig as fact
      ansible.builtin.set_fact:
        mgmt_kubeconfig_content: "{{ mgmt_kubeconfig_data['content'] | b64decode }}"


- name: Deploy RKE2 on the Mgmt Cluster - CP Others
  hosts: mgmt_cp_others
  tasks:
    - name: Deploy RKE2 cp others
      import_role:
        name: rke2
      vars:
        rke2endpoint: "{{ hostvars['localhost']['kubeapi_fqdn'] }}"
        service_name: "rke2-server"
        token: "{{ cluster.token | default('mgmt-rke2token') }}"
        version: "{{ cluster.version | default('v1.30.5+rke2r1') }}"
        role: control-plane-others

    #https://github.com/NVIDIA/gpu-operator/issues/992#issuecomment-2796578769
    - name: Update PATH
      become: true
      shell: |
        echo PATH=$PATH:/usr/local/nvidia/toolkit >> /etc/default/rke2-server

- name: Deploy RKE2 on the Mgmt Cluster - Agents
  hosts: mgmt_agents
  tasks:
    - name: Deploy RKE2 agents
      import_role:
        name: rke2
      vars:
        rke2endpoint: "{{ hostvars['localhost']['kubeapi_fqdn'] }}"
        service_name: "rke2-agent"
        token: "{{ cluster.token | default('mgmt-rke2token') }}"
        version: "{{ cluster.version | default('v1.30.5+rke2r1') }}"
        role: agent

      #https://github.com/NVIDIA/gpu-operator/issues/992#issuecomment-2796578769
    - name: Update PATH
      become: true
      shell: |
        echo PATH=$PATH:/usr/local/nvidia/toolkit >> /etc/default/rke2-agent

- name: Copy kubeconfig
  hosts: mgmt_cp_others:mgmt_agents
  tasks:
    - name: Create kubeconfig directory
      ansible.builtin.file:
        path: "/home/{{ vm_ansible_user | default('ai') }}/.kube"
        state: directory
        mode: '0755'

    - name: Copy kubeconfig
      ansible.builtin.copy:
        dest: "/home/{{ vm_ansible_user | default('ai') }}/.kube/config"
        content: "{{ hostvars[groups['mgmt_cp_master'][0]]['mgmt_kubeconfig_content'] }}"

- name: Deploy local-path provisioner
  hosts: mgmt_cp_master
  tasks:
    - name: Deploy local-path provisioner
      import_role:
        name: local-path
      when: not (enable_longhorn | default(false) | bool)
