- name: Read tofu output
  import_playbook: read_tofu_output.yml

- name: Display SSH access
  import_playbook: ssh-access.yml

- name: Deploy SUSE Observability
  hosts: rke2_servers[0]
  tasks:
    - block:
      - name: Set AI and Observabilty IP
        set_fact:
          suse_ai_vm_ip: "{{ hostvars['localhost']['suse_ai_vm_ip'] | default(hostvars['localhost']['vm_ip']) }}"
          suse_observability_vm_ip: "{{ hostvars['localhost']['suse_observability_vm_ip'] | default(hostvars['localhost']['vm_ip']) }}"

      - name: Update core dns entries on suse-observability cluster
        import_role: 
          name: update-coredns
        vars:
          host_entries: |
            {{
              [hostvars['localhost']['vm_ip'] ~ ' ' ~ hostvars['localhost']['rancher_host'] ]
              + ([suse_observability_vm_ip ~ ' ' ~ hostvars['localhost']['suse_observability_host']] if enable_suse_observability | default(false) else [])
              + ([suse_observability_vm_ip ~ ' ' ~ hostvars['localhost']['suse_observability_otel_host']] if enable_suse_observability | default(false) else [])
            }}
        when: not (enable_external_dns | default(false)) and suse_observability_cluster is defined and enable_suse_observability | default(false)

      - name: Set target when no external-dns
        set_fact:
          suse_observability_target: "{{ ansible_host }}"
        when: not ( enable_external_dns | default(false))

      - name: Set target when external-dns
        set_fact:
          suse_observability_target: "{{ hostvars['localhost']['suse_observability_ingress_fqdn'] | default(hostvars['localhost']['ingress_fqdn']) }}"
        when: enable_external_dns | default(false)

      - name: Deploy SUSE Observability
        import_role:
          name: suse-observability
        vars:
          suse_observability_host: "{{ hostvars['localhost']['suse_observability_host'] }}"
          suse_observability_otel_host: "{{ hostvars['localhost']['suse_observability_otel_host'] }}"
          cluster_name: "{{ 'suse-ai' if suse_ai_cluster is defined else 'local' }}"

      - name: Get rancher token
        import_role:
          name: rancher-token
        vars:
          rancher_host: "{{ hostvars['localhost']['rancher_host'] }}"
          rancher_bootstrap_password: "{{ rancher_boostrap_password | default('rancher') }}"
        when: suse_observability_cluster is defined and enable_suse_observability | default(false)
        
      - name: Import suse_observability_cluster
        import_role:
          name: import-cluster
        vars:
          rancher_url: "https://{{ hostvars['localhost']['rancher_host'] }}"
          rancher_token: "{{ hostvars['mgmt-rancher']['rancher_token'] }}"
          cluster_name: suse-observability
        when: suse_observability_cluster is defined and enable_suse_observability | default(false)
      
      - name: Show SUSE AI VM login
        debug:
          msg: |
            "SUSE Observability kubeapi: {{ hostvars['localhost']['suse_observability_kubeapi_fqdn'] | default(hostvars['localhost']['kubeapi_fqdn']) }}"
            "SUSE Observability ingress: {{ hostvars['localhost']['suse_observability_ingress_fqdn'] | default(hostvars['localhost']['ingress_fqdn']) }}"
            "Login to the suse-observability vm with 'ssh {{ hostvars['localhost']['vm_ansible_user'] | default('ai') }}@{{ hostvars['localhost']['suse_observability_vm_ip'] | default(hostvars['localhost']['vm_ip'])}}'"
      when: enable_suse_observability | default(false)
