- name: Deploy RKE2 on SUSE Observability cluster - CP Master
  hosts: suse_observability_cp_master
  tasks:
    - name: Deploy RKE2 master
      import_role:
        name: rke2
      vars:
        rke2endpoint: "{{ hostvars['localhost']['suse_observability_kubeapi_fqdn'] }}"
        service_name: "rke2-server"
        token: "{{ suse_observability_cluster.token | default('suse-observability-rke2token') }}"
        version: "{{ suse_observability_cluster.version | default('v1.30.5+rke2r1') }}"
        role: control-plane-master
        cluster_name: "{% if suse_observability_cluster is defined %}suse-observability{% endif %}"

    #https://github.com/NVIDIA/gpu-operator/issues/992#issuecomment-2796578769
    - name: Update PATH
      become: true
      shell: |
        echo PATH=$PATH:/usr/local/nvidia/toolkit >> /etc/default/rke2-server

    - name: Read kubeconfig from master node
      ansible.builtin.slurp:
        src: "/home/{{ vm_ansible_user | default('ai') }}/.kube/config"
      register: suse_observability_kubeconfig_data
      become: true

    - name: Set kubeconfig as fact
      ansible.builtin.set_fact:
        suse_observability_kubeconfig_content: "{{ suse_observability_kubeconfig_data['content'] | b64decode }}"

- name: Deploy RKE2 on SUSE Observability cluster - CP Others
  hosts: suse_observability_cp_others
  tasks:
    - name: Deploy RKE2 cp others
      import_role:
        name: rke2
      vars:
        rke2endpoint: "{{ hostvars['localhost']['suse_observability_kubeapi_fqdn'] }}"
        service_name: "rke2-server"
        token: "{{ suse_observability_cluster.token | default('suse-observability-rke2token') }}"
        version: "{{ suse_observability_cluster.version | default('v1.30.5+rke2r1') }}"
        role: control-plane-others
        cluster_name: "{% if suse_observability_cluster is defined %}suse-observability{% endif %}"

    #https://github.com/NVIDIA/gpu-operator/issues/992#issuecomment-2796578769
    - name: Update PATH
      become: true
      shell: |
        echo PATH=$PATH:/usr/local/nvidia/toolkit >> /etc/default/rke2-server

- name: Deploy RKE2 on SUSE Observability cluster - Agents
  hosts: suse_observability_agents
  tasks:
    - name: Deploy RKE2 agents
      import_role:
        name: rke2
      vars:
        rke2endpoint: "{{ hostvars['localhost']['suse_observability_kubeapi_fqdn'] }}"
        service_name: "rke2-agent"
        token: "{{ suse_observability_cluster.token | default('suse-observability-rke2token') }}"
        version: "{{ suse_observability_cluster.version | default('v1.30.5+rke2r1') }}"
        role: agent
        cluster_name: "{% if suse_observability_cluster is defined %}suse-observability{% endif %}"

      #https://github.com/NVIDIA/gpu-operator/issues/992#issuecomment-2796578769
    - name: Update PATH
      become: true
      shell: |
        echo PATH=$PATH:/usr/local/nvidia/toolkit >> /etc/default/rke2-agent

- name: Copy kubeconfig
  hosts: suse_observability_cp_others:suse_observability_agents
  tasks:
    - name: Create kubeconfig directory
      ansible.builtin.file:
        path: "/home/{{ vm_ansible_user | default('ai') }}/.kube"
        state: directory
        mode: '0755'

    - name: Copy kubeconfig
      ansible.builtin.copy:
        dest: "/home/{{ vm_ansible_user | default('ai') }}/.kube/config"
        content: "{{ hostvars[groups['suse_observability_cp_master'][0]]['suse_observability_kubeconfig_content'] }}"


- name: Deploy local-path provisioner suse-observability cluster
  hosts: suse_observability_cp_master
  tasks:
    - name: Deploy local-path provisioner observability cluster
      import_role:
        name: local-path
      when: not (enable_longhorn | default(false) | bool)