---
- name: Fetch Resources
  hosts: localhost
  connection: local
  tasks:
    - name: Fetch tofu output
      shell: |
        tofu output --json
      args:
        chdir: "{{ (current_project_dir, 'roles/vm/terraform') | path_join }}"
      register: tfstate
      when: cloud_provider | default('local') != "local"

    - name: Set tofu output
      set_fact:
        tofu_outputs: "{{ tfstate.stdout | from_json }}"
      when: cloud_provider | default('local') != "local"

    - name: Display tofu output
      debug:
        msg: "{{ tofu_outputs }}"
      when: cloud_provider | default('local') != "local"

    - name: Extract mgmt cluster tofu output
      include_role:
        name: vm
        tasks_from: mgmt_cluster_output

    - name: Extract suse-ai cluster tofu output
      include_role:
        name: vm
        tasks_from: suse_ai_cluster_output
      when: suse_ai_cluster is defined

    - name: Extract suse-observability cluster tofu output
      include_role:
        name: vm
        tasks_from: suse_observability_cluster_output
      when: suse_observability_cluster is defined and enable_suse_observability | default('False') | bool

    - name: Include ingress_ouput
      include_role:
        name: vm
        tasks_from: ingress_output.yml

- name: Setup the right python interpreter based on the distro
  import_playbook: setup_python_interpreter.yml

- name: Define mgmt cluster nodes
  import_playbook: define_nodes_mgmt_cluster.yml
  vars:
    python_interpreter: "{{ hostvars['localhost']['python_interpreter'] }}"

- name: Define suse ai cluster nodes
  import_playbook: define_nodes_suse_ai_cluster.yml
  vars:
    suse_ai_python_interpreter: "{{ hostvars['localhost']['suse_ai_python_interpreter'] }}"
  when: suse_ai_cluster is defined

- name: Define suse observability cluster nodes
  import_playbook: define_nodes_suse_observability_cluster.yml
  vars:
    suse_observability_python_interpreter: "{{ hostvars['localhost']['suse_observability_python_interpreter'] }}"
  when: suse_observability_cluster is defined and enable_suse_observability | default('False') | bool

- hosts: mgmt_master:suse_ai_master:suse_observability_master
  gather_facts: false
  tasks:
    # We want to cleanup the DNS records before deleting the stack.
    # Just Uninstalling the external-dns does not cleanup the records.
    # Deleting ingress resources first ensures that ExternalDNS has a chance to
    # remove the associated DNS records before it's removed from the cluster.
    - name: Remove Ingress
      shell: |
        #!/bin/bash
        ingresses_json=$(kubectl get ingresses --all-namespaces -o json)
        ingresses_array=$(echo "$ingresses_json" | jq -c '.items[]')
        for ingress in $ingresses_array; do
          name=$(echo "$ingress" | jq -r '.metadata.name')
          namespace=$(echo "$ingress" | jq -r '.metadata.namespace')
          kubectl delete ingress $name -n $namespace
        done
        sleep 60
      when: enable_external_dns | default(false)

    - name: Uninstall external-dns
      import_role:
        name: external-dns
      vars:
        uninstall: true
      when: enable_external_dns | default(false)
      ignore_errors: true

- hosts: mgmt_cluster:suse_ai_cluster:suse_observability_cluster
  gather_facts: true
  tasks:
    # deregister from SCC
    - name: De-register
      import_role:
        name: deregister
      ignore_errors: true

- name: Destroy Resources
  hosts: localhost
  connection: local
  tasks:
    - name: Destroy Resources
      include_role:
        name: vm
      vars:
        vm_action: destroy
        vm_instance_name: mgmt-rancher
