---

- name: Read tofu output
  import_playbook: read_tofu_output.yml

- name: Display Control Plane Master Node IP
  import_playbook: ssh-access.yml

- name: Display Access URL and credentials
  hosts: localhost
  connection: local
  tasks:
    - name: Read suse observabiltiy admin password
      ansible.builtin.slurp:
        src: "../suse_observability_admin_password.txt"
      register: suse_observability_admin_password_file_contents
      when: enable_suse_observability | default(false)

    - name: Prepare /etc/hosts entries (short hostnames)
      set_fact:
        hosts_entries: "{{ hosts_entries | default([]) + [ item.entry ] }}"
      when: item.eval
      with_items:
        - entry: "{{ vm_ip }} mgmt-rancher"
          eval: true
        - entry: "{{ hostvars['localhost']['suse_ai_vm_ip'] | default(hostvars['localhost']['vm_ip'])}} suse-ai"
          eval: true
        - entry: "{{ vm_ip }} longhorn"
          eval: "{{ enable_longhorn | default(False) | bool }}"
        - entry: "{{ hostvars['localhost']['suse_observability_vm_ip'] | default(hostvars['localhost']['vm_ip'])}} suse-observability"
          eval: "{{ enable_suse_observability | default(False) | bool }}"

    - name: Prepare URL entries (FQDNs)
      set_fact:
        url_entries: "{{ url_entries | default([]) + [ item.entry ] }}"
      when: item.eval
      with_items:
        - entry: "{{ vm_ip }} {{ rancher_host }}"
          eval: "{{ not (enable_external_dns | default(False)) }}"
        - entry: "{{ hostvars['localhost']['suse_ai_vm_ip'] | default(hostvars['localhost']['vm_ip'])}} {{ open_webui_host }}"
          eval: "{{ not (enable_external_dns | default(False)) }}"
        - entry: "{{ vm_ip }} {{ longhorn_host }}"
          eval: "{{ not (enable_external_dns | default(False)) and (enable_longhorn | default(False) | bool) }}"
        - entry: "{{ hostvars['localhost']['suse_observability_vm_ip'] | default(hostvars['localhost']['vm_ip'])}} {{ suse_observability_host }}"
          eval: "{{ not (enable_external_dns | default(False)) and (enable_suse_observability | default(False) | bool) }}"

    - name: Display /etc/hosts entries
      debug:
        msg:
        - "Add these items to /etc/hosts as line entries:"
        - "{{ (hosts_entries | default([]) + url_entries | default([])) | join(', ') }}"
      when: (hosts_entries is defined and hosts_entries | length > 0) or (url_entries is defined and url_entries | length > 0)

    - name: Write host entries to suse_ai_stack_host_entries
      copy:
        dest: "/tmp/suse_ai_stack_host_entries"
        content: "{{ (hosts_entries | default([]) + url_entries | default([])) | join('\n') }}\n"
      when: (hosts_entries is defined and hosts_entries | length > 0) or (url_entries is defined and url_entries | length > 0)

    - name: Set Access URL and credentials
      set_fact:
        access_msg: "{{ access_msg | default([]) + [ item.msg | string ] }}"
      when: item.eval
      with_items:
        - msg: "To access rancher UI, point your browser to https://{{ rancher_host }} and login with user=admin and password={{ rancher_bootstrap_password | default('rancher')  }}"
          eval: true
        - msg: "To access longhorn UI, point your browser to http://{{ longhorn_host }} and login with user={{ longhorn_username | default('admin')}} and password={{  longhorn_password | default('longhorn')}}"
          eval: "{{ enable_longhorn | default(False) | bool }}"
        - msg: "To access open-webui, point your browser to https://{{ open_webui_host }} and login with user={{ open_webui_admin_email | default('admin@suse-private-ai.org') }} and password={{ open_webui_admin_password | default('WelcomeToAI') }}"
          eval: "{{ not deploy_rancher_only | default(False) | bool }}"
        - msg: "To access suse-observability, point your browser to https://{{ suse_observability_host }} and login with user=admin and password={{ (suse_observability_admin_password_file_contents.content | default('')) | b64decode | trim }}"
          eval: "{{ enable_suse_observability | default(False) | bool }}"

    - name: Show Access URL and credentials
      debug:
        msg: "{{ access_msg }}"

    - name: Output access msg to a file
      copy:
        dest: "/tmp/suse_ai_stack_access"
        content: "{{ access_msg }}"

    - name: Display note
      debug:
        msg:
          - "Note: the terminal output shown above is no longer accessible once exited,"
          - "but the same information is saved in /tmp/suse_ai_stack_host_entries and"
          - "/tmp/suse_ai_stack_access for later reference."
