---
- name: Import SUSE Observability cluster
  hosts: suse_observability_cp_master
  tasks:

  - name: Import suse_observability_cluster
    import_role:
      name: import-cluster
    vars:
      rancher_url: "https://{{ hostvars['localhost']['rancher_host'] }}"
      rancher_token: "{{ hostvars['mgmt-rancher']['rancher_token'] }}"
      cluster_name: suse-observability
