- name: Register and Install Packages on all nodes
  hosts: mgmt_cluster:suse_ai_cluster:suse_observability_cluster
  tasks:
    - name: Upload additional SSH pubkeys
      ansible.posix.authorized_key:
        user: "{{ vm_ansible_user | default('ai') }}"
        key: "{{ item }}"
      loop: "{{ additional_public_keys | default([]) }}"

    - name: Registration sle-micro
      become: true
      shell: |
        transactional-update register --url {{ registration_server | default("https://scc.suse.com") }} --email {{ registration_email }} --regcode "{{ registration_code }}"
      when: ansible_distribution == 'SL-Micro'
      register: register_result
      failed_when: "'Error' in register_result.stdout"

    - name: Print ansible host name
      debug:
        msg: "ansible host name is {{ inventory_hostname }}"

    - name: Set the hostname
      become: true
      shell: >
        hostnamectl set-hostname "{{ inventory_hostname }}"

    - name: Add SUSE internal CA certificate
      import_role:
        name: suse-ca-certificate

    - name: Install Kubernetes tools and utilities
      import_role:
        name: kubernetes-tools

    - name: Install Packages
      include_role:
        name: vm
        tasks_from: install_suse_package
