- name: Update /etc/hosts entry
  hosts: mgmt_cp_master:suse_ai_cp_master:suse_observability_cp_master
  tasks:
    - name: Add Rancher host to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        line: "{{ vm_ip }} mgmt-rancher {{ rancher_host }}"

    - name: Add SUSE AI host to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        line: "{{ suse_ai_vm_ip }} {{ open_webui_host }}"

    - name: Add SUSE Observability host to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        line: "{{ suse_observability_vm_ip }} {{ suse_observability_host }}"