suse_observability_namespace: suse-observability
suse_observability_helm_repo_url: https://charts.rancher.com/server-charts/prime/suse-observability
suse_observability_helm_repo_name: suse-observability
suse_observability_agent_helm_chart_name: suse-observability-agent
suse_observability_agent_helm_chart_ref: "{{ suse_observability_helm_repo_name }}/{{ suse_observability_agent_helm_chart_name }}"
suse_observability_api_token: suseobservability
appco_secret: application-collection
stackstate_cluster_name: "{{ cluster_name | default('local', true) }}"
stackstate_url: "{{ ss_url | default('http://suse-observability-router.' ~ suse_observability_namespace ~ '.svc.cluster.local:8080/receiver/stsAgent', true) }}"
